// panel/src/App.tsx
import { Login } from './components/Login';
import { Dashboard } from './components/Dashboard';
import { useAuth } from './hooks/useAuth';

function App() {
  // Usa variable de entorno o la URL tunelizada si existe
  const VITE_API_URL = import.meta.env.VITE_API_URL || 'https://vps-a70_backend.humanibot.online';
  // Usa URL pública si existe (VITE_API_URL) o detecta automáticamente el host
  const serverUrl = VITE_API_URL || `${window.location.protocol}//${window.location.hostname}:3001`;
  const { token, username, isAuthenticated, isLoading, error, login, logout } = useAuth(serverUrl);

  const handleLogin = async (user: string, password: string) => {
    return await login(user, password);
  };

  if (!isAuthenticated) {
    return <Login onLogin={handleLogin} isLoading={isLoading} error={error} />;
  }

  return (
    <Dashboard
      serverUrl={serverUrl}
      token={token!}
      username={username!}
      onLogout={logout}
    />
  );
}

export default App;

// panel/src/app/app.component.ts
import { Component, computed, signal } from '@angular/core';
import { NgIf } from '@angular/common';
import { environment } from '../environments/environment';
import { AuthService } from './services/auth.service';
import { LoginComponent } from './components/login/login.component';
import { DashboardComponent } from './components/dashboard/dashboard.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [NgIf, LoginComponent, DashboardComponent],
  template: `
    <ng-container *ngIf="!isAuthenticated(); else dashboard">
      <app-login
        [isLoading]="auth.isLoading()"
        [error]="auth.error()"
        (login)="onLogin($event.username, $event.password)"
      ></app-login>
    </ng-container>
    <ng-template #dashboard>
      <app-dashboard
        [serverUrl]="serverUrl"
        [token]="auth.token()!"
        [username]="auth.username() || ''"
        (logout)="onLogout()"
      ></app-dashboard>
    </ng-template>
  `
})
export class AppComponent {
  serverUrl = environment.apiUrl || `${window.location.protocol}//${window.location.hostname}:3001`;
  isAuthenticated = computed(() => !!this.auth.token());

  constructor(public auth: AuthService) {}

  async onLogin(username: string, password: string) {
    await this.auth.login(this.serverUrl, username, password);
  }

  async onLogout() {
    await this.auth.logout(this.serverUrl);
  }
}
